version: '3.2'
services: 
  product-service:
    build: 
      context: ./product-service
    ports:
      - "8000:3000"
    environment:
      - test=testvalue
    volumes:
      - type: bind
        source: ./product-service
        target: /app
  inventory-service: 
    build:
      context: ./inventory-service
    ports:
      - "8001:3000"
    volumes:
      - my-volume:/var/lib/data
  product-db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=complexpassword
    ports:
      - 8002:3306

volumes:  
  my-volume:
